# Generated by TSG author, 2026.

"""
QCNet Agent Encoder with TSGFormer for agent-agent relationships (Argoverse2).

TSGFormer is applied to selected key frames to enrich agent representations
with global scene context via structured attention biases.
"""
from typing import Dict, List, Optional

import torch
import torch.nn as nn
from torch_cluster import radius
from torch_cluster import radius_graph
from torch_geometric.data import Batch
from torch_geometric.utils import dense_to_sparse, subgraph

from layers.attention_layer import AttentionLayer
from layers.fourier_embedding import FourierEmbedding
from modules.tsgformer_components import TSGFormerGraphEncoder, Pl2aTSGFormerLayer
from utils import angle_between_2d_vectors, weight_init, wrap_angle


class QCNetAgentEncoderWithTSGFormer(nn.Module):
    """
    Temporal attention + Map→Agent attention + TSGFormer on key frames.

    TSGFormer is applied to a set of selected key frames after the standard
    temporal and map-agent encoding layers, enriching each frame's agent
    representations with global scene context.
    """

    def __init__(self,
                 dataset: str,
                 input_dim: int,
                 hidden_dim: int,
                 num_historical_steps: int,
                 time_span: Optional[int],
                 pl2a_radius: float,
                 a2a_radius: float,
                 num_freq_bands: int,
                 num_agent_layers: int,
                 num_heads: int,
                 head_dim: int,
                 dropout: float,
                 tsgformer_key_frames: Optional[List[int]] = None,
                 num_agent_types: int = 6,
                 num_speed_bins: int = 50,
                 num_spatial_bins: int = 200,
                 num_ttc_bins: int = 100,
                 num_edge_types: int = 21,
                 use_pl2a_tsgformer: bool = True,
                 num_pl2a_edge_types: int = 8,
                 num_ttr_bins: int = 50,
                 residual_gate_init: float = -2.0,
                 **kwargs) -> None:
        super().__init__()
        self.dataset = dataset
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.num_historical_steps = num_historical_steps
        self.time_span = time_span if time_span is not None else num_historical_steps
        self.pl2a_radius = pl2a_radius
        self.a2a_radius = a2a_radius
        self.num_freq_bands = num_freq_bands
        self.num_layers = num_agent_layers
        self.num_heads = num_heads
        self.head_dim = head_dim
        self.dropout = dropout
        self.use_pl2a_tsgformer = use_pl2a_tsgformer
        self.s_min = kwargs.get('s_min', 0.5)
        self.lane_eps = kwargs.get('lane_eps', 0.05)
        self.ttr_lateral_scale = kwargs.get('ttr_lateral_scale', 4.0)
        self.ttr_backward_scale = kwargs.get('ttr_backward_scale', 6.0)
        self.road_reach_time = kwargs.get('road_reach_time', 6.0)

        # Default key frames: every ~2.5s for 50 historical steps at 10Hz
        if tsgformer_key_frames is None:
            self.key_frames = [9, 29, 49] if num_historical_steps == 50 else [num_historical_steps - 1]
        else:
            self.key_frames = tsgformer_key_frames

        if dataset != 'argoverse_v2':
            raise ValueError(f'{dataset} is not a valid dataset')

        input_dim_x_a = 4
        input_dim_r_t = 4
        input_dim_r_pl2a = 3

        self.type_a_emb = nn.Embedding(10, hidden_dim)
        self.x_a_emb = FourierEmbedding(input_dim=input_dim_x_a, hidden_dim=hidden_dim, num_freq_bands=num_freq_bands)
        self.r_t_emb = FourierEmbedding(input_dim=input_dim_r_t, hidden_dim=hidden_dim, num_freq_bands=num_freq_bands)

        self.t_attn_layers = nn.ModuleList(
            [AttentionLayer(hidden_dim=hidden_dim, num_heads=num_heads, head_dim=head_dim, dropout=dropout,
                            bipartite=False, has_pos_emb=True) for _ in range(self.num_layers)]
        )

        if self.use_pl2a_tsgformer:
            self.pl2a_tsgformer_layers = nn.ModuleList([
                Pl2aTSGFormerLayer(
                    hidden_dim=hidden_dim, num_heads=num_heads, head_dim=head_dim, dropout=dropout,
                    num_freq_bands=num_freq_bands, num_spatial_bins=100, num_directional_bins=36,
                    num_pl2a_edge_types=num_pl2a_edge_types, num_ttr_bins=num_ttr_bins,
                    max_distance=pl2a_radius
                ) for _ in range(self.num_layers)
            ])
            self.pl2a_residual_gates = nn.ParameterList([
                nn.Parameter(torch.tensor(residual_gate_init)) for _ in range(self.num_layers)
            ])
        else:
            self.r_pl2a_emb = FourierEmbedding(input_dim=input_dim_r_pl2a, hidden_dim=hidden_dim,
                                               num_freq_bands=num_freq_bands)
            self.pl2a_attn_layers = nn.ModuleList(
                [AttentionLayer(hidden_dim=hidden_dim, num_heads=num_heads, head_dim=head_dim, dropout=dropout,
                                bipartite=True, has_pos_emb=True) for _ in range(self.num_layers)]
            )

        self.tsgformer_encoder = TSGFormerGraphEncoder(
            num_heads=num_heads,
            num_agent_types=num_agent_types,
            num_speed_bins=num_speed_bins,
            num_spatial_bins=num_spatial_bins,
            num_ttc_bins=num_ttc_bins,
            num_edge_types=num_edge_types,
            hidden_dim=hidden_dim,
            num_layers=num_agent_layers,
            dropout=dropout,
        )

        self.apply(weight_init)

        print(f"[QCNetAgentEncoderWithTSGFormer] Initialized with:")
        print(f"  - use_pl2a_tsgformer: {use_pl2a_tsgformer}")

    def _apply_tsgformer_batched(self, x_a_t: torch.Tensor, pos_t: torch.Tensor,
                                  vel_t: torch.Tensor, agent_types: torch.Tensor,
                                  agent_batch: Optional[torch.Tensor],
                                  g_map: Optional[torch.Tensor] = None) -> tuple:
        """Apply TSGFormer per scene, return (enhanced_agent_feats, per_agent_scene_tokens).

        Scenes with ≤1 agent are skipped and receive zero tokens.
        """
        out_feats = x_a_t.clone()
        scene_tokens = x_a_t.new_zeros(x_a_t.size(0), self.hidden_dim)

        if agent_batch is None:
            feats, scene_tok = self.tsgformer_encoder(x_a_t, pos_t, vel_t, agent_types, g_map=g_map)
            out_feats = feats
            scene_tokens = scene_tok.unsqueeze(0).expand(x_a_t.size(0), -1)
        else:
            for b in agent_batch.unique():
                mask = (agent_batch == b)
                if mask.sum() <= 1:
                    continue
                g_map_b = None
                if g_map is not None:
                    g_map_b = g_map[mask][:, mask]
                feats_b, scene_tok_b = self.tsgformer_encoder(
                    x_a_t[mask], pos_t[mask], vel_t[mask], agent_types[mask], g_map=g_map_b)
                out_feats[mask] = feats_b
                scene_tokens[mask] = scene_tok_b.unsqueeze(0).expand(mask.sum(), -1)

        return out_feats, scene_tokens

    def _apply_pl2a_tsgformer(self,
                               x_a: torch.Tensor,
                               map_enc_x_pl: torch.Tensor,
                               edge_index_pl2a: torch.Tensor,
                               rel_pos_pl2a: torch.Tensor,
                               head_s: torch.Tensor,
                               orient_pl_rep: torch.Tensor,
                               speed_s: torch.Tensor,
                               pos_s: torch.Tensor,
                               edge_index_pl2pl: Optional[torch.Tensor],
                               edge_type_pl2pl: Optional[torch.Tensor],
                               layer_idx: int) -> torch.Tensor:
        """Apply Pl2a TSGFormer layer (Map as K/V, Agent as Query)."""
        x_pl_flat = map_enc_x_pl.transpose(0, 1).reshape(-1, self.hidden_dim)
        agent_heading_edges = head_s[edge_index_pl2a[1]]
        rel_angle = torch.atan2(rel_pos_pl2a[:, 1], rel_pos_pl2a[:, 0])
        relative_angle = wrap_angle(rel_angle - agent_heading_edges)
        distances = torch.norm(rel_pos_pl2a[:, :2], p=2, dim=-1)
        lane_heading = orient_pl_rep[edge_index_pl2a[0]]
        delta_heading = wrap_angle(lane_heading - agent_heading_edges)
        lane_tangent = torch.stack([lane_heading.cos(), lane_heading.sin()], dim=-1)
        lane_normal = torch.stack([-lane_heading.sin(), lane_heading.cos()], dim=-1)
        d_parallel = (rel_pos_pl2a[:, :2] * lane_tangent).sum(dim=-1)
        d_perp = (rel_pos_pl2a[:, :2] * lane_normal).sum(dim=-1).abs()
        lane_plausibility = ((1.0 + delta_heading.cos()) * 0.5 *
                             torch.exp(-d_perp / self.ttr_lateral_scale) *
                             torch.exp(-torch.clamp(-d_parallel, min=0.0) / self.ttr_backward_scale))
        edge_types = torch.full((edge_index_pl2a.size(1),), 7, dtype=torch.long, device=x_a.device)
        lane_gate = lane_plausibility > self.lane_eps
        edge_types[lane_gate] = 6
        centrality = torch.exp(-distances / self.pl2a_radius).clamp(min=0.1, max=1.0)
        speed_edges = speed_s[edge_index_pl2a[1]].clamp(min=self.s_min)
        ttr = (d_perp + torch.clamp(d_parallel, min=0.0)) / speed_edges
        ttr[~lane_gate] = float('inf')
        x_a_orig = x_a.clone()
        x_a = self.pl2a_tsgformer_layers[layer_idx](
            x_src=x_pl_flat,
            x_dst=x_a,
            edge_index=edge_index_pl2a,
            rel_pos=rel_pos_pl2a[:, :2],
            relative_angle=relative_angle,
            edge_types=edge_types,
            ttr_values=ttr,
            centrality=centrality
        )
        alpha = torch.sigmoid(self.pl2a_residual_gates[layer_idx])
        x_a = (1 - alpha) * x_a_orig + alpha * x_a
        return x_a

    def _build_road_gate(self,
                         pos_t: torch.Tensor,
                         head_t: torch.Tensor,
                         vel_t: torch.Tensor,
                         pos_pl: torch.Tensor,
                         orient_pl: torch.Tensor,
                         edge_index_pl2pl: Optional[torch.Tensor]) -> torch.Tensor:
        num_agents = pos_t.size(0)
        if num_agents == 0:
            return pos_t.new_zeros((0, 0))

        rel = pos_pl.unsqueeze(0) - pos_t.unsqueeze(1)  # [N, M, 2]
        lane_heading = orient_pl.unsqueeze(0).expand(num_agents, -1)
        delta_heading = wrap_angle(lane_heading - head_t.unsqueeze(1))
        lane_tangent = torch.stack([lane_heading.cos(), lane_heading.sin()], dim=-1)
        lane_normal = torch.stack([-lane_heading.sin(), lane_heading.cos()], dim=-1)
        d_parallel = (rel * lane_tangent).sum(dim=-1)
        d_perp = (rel * lane_normal).sum(dim=-1).abs()
        lane_plausibility = ((1.0 + delta_heading.cos()) * 0.5 *
                             torch.exp(-d_perp / self.ttr_lateral_scale) *
                             torch.exp(-torch.clamp(-d_parallel, min=0.0) / self.ttr_backward_scale))
        speeds = torch.norm(vel_t.float(), p=2, dim=-1).clamp(min=self.s_min).unsqueeze(1)
        ttr = (d_perp + torch.clamp(d_parallel, min=0.0)) / speeds
        reachable = (lane_plausibility > self.lane_eps) & (ttr < self.road_reach_time)

        if edge_index_pl2pl is not None and edge_index_pl2pl.size(1) > 0:
            src, dst = edge_index_pl2pl
            reachable_hop = reachable.clone()
            reachable_hop[:, dst] |= reachable[:, src]
            reachable = reachable | reachable_hop

        shared = torch.matmul(reachable.float(), reachable.float().T) > 0
        return shared.float()

    def forward(self,
                map_enc_x_pl: torch.Tensor,
                mask: torch.Tensor,
                pos_a: torch.Tensor,
                motion_vector_a: torch.Tensor,
                head_a: torch.Tensor,
                pos_pl: torch.Tensor,
                orient_pl: torch.Tensor,
                vel: torch.Tensor,
                agent_type: torch.Tensor,
                batch_s: torch.Tensor,
                batch_pl: torch.Tensor,
                edge_index_pl2pl: Optional[torch.Tensor] = None,
                edge_type_pl2pl: Optional[torch.Tensor] = None,
                agent_batch: Optional[torch.Tensor] = None) -> Dict[str, torch.Tensor]:

        categorical_embs = [self.type_a_emb(agent_type).repeat_interleave(self.num_historical_steps, dim=0)]

        head_vector_a = torch.stack([head_a.cos(), head_a.sin()], dim=-1)
        x_a = torch.stack(
            [torch.norm(motion_vector_a[:, :, :2], p=2, dim=-1),
             angle_between_2d_vectors(ctr_vector=head_vector_a, nbr_vector=motion_vector_a[:, :, :2]),
             torch.norm(vel[:, :, :2], p=2, dim=-1),
             angle_between_2d_vectors(ctr_vector=head_vector_a, nbr_vector=vel[:, :, :2])], dim=-1)
        x_a = self.x_a_emb(continuous_inputs=x_a.view(-1, x_a.size(-1)), categorical_embs=categorical_embs)
        x_a = x_a.view(-1, self.num_historical_steps, self.hidden_dim)

        # Temporal edges
        pos_t = pos_a.reshape(-1, self.input_dim)
        head_t = head_a.reshape(-1)
        head_vector_t = head_vector_a.reshape(-1, 2)
        mask_t = mask.unsqueeze(2) & mask.unsqueeze(1)
        edge_index_t = dense_to_sparse(mask_t)[0]
        edge_index_t = edge_index_t[:, edge_index_t[1] > edge_index_t[0]]
        edge_index_t = edge_index_t[:, edge_index_t[1] - edge_index_t[0] <= self.time_span]
        rel_pos_t = pos_t[edge_index_t[0]] - pos_t[edge_index_t[1]]
        rel_head_t = wrap_angle(head_t[edge_index_t[0]] - head_t[edge_index_t[1]])
        r_t = torch.stack(
            [torch.norm(rel_pos_t[:, :2], p=2, dim=-1),
             angle_between_2d_vectors(ctr_vector=head_vector_t[edge_index_t[1]], nbr_vector=rel_pos_t[:, :2]),
             rel_head_t,
             edge_index_t[0] - edge_index_t[1]], dim=-1)
        r_t = self.r_t_emb(continuous_inputs=r_t, categorical_embs=None)

        # Map→Agent edges
        pos_s = pos_a.transpose(0, 1).reshape(-1, self.input_dim)
        head_s = head_a.transpose(0, 1).reshape(-1)
        head_vector_s = head_vector_a.transpose(0, 1).reshape(-1, 2)
        mask_s = mask.transpose(0, 1).reshape(-1)
        pos_pl_rep = pos_pl.repeat(self.num_historical_steps, 1)
        orient_pl_rep = orient_pl.repeat(self.num_historical_steps)
        speed_s = torch.norm(vel.transpose(0, 1).reshape(-1, self.input_dim).float(), p=2, dim=-1)

        edge_index_pl2a = radius(x=pos_s[:, :2], y=pos_pl_rep[:, :2], r=self.pl2a_radius,
                                 batch_x=batch_s, batch_y=batch_pl, max_num_neighbors=300)
        edge_index_pl2a = edge_index_pl2a[:, mask_s[edge_index_pl2a[1]]]
        rel_pos_pl2a = pos_pl_rep[edge_index_pl2a[0]] - pos_s[edge_index_pl2a[1]]
        rel_orient_pl2a = wrap_angle(orient_pl_rep[edge_index_pl2a[0]] - head_s[edge_index_pl2a[1]])
        if not self.use_pl2a_tsgformer:
            r_pl2a = torch.stack(
                [torch.norm(rel_pos_pl2a[:, :2], p=2, dim=-1),
                 angle_between_2d_vectors(ctr_vector=head_vector_s[edge_index_pl2a[1]], nbr_vector=rel_pos_pl2a[:, :2]),
                 rel_orient_pl2a], dim=-1)
            r_pl2a = self.r_pl2a_emb(continuous_inputs=r_pl2a.float(), categorical_embs=None)

        # Temporal + Map-Agent encoding layers
        for i in range(self.num_layers):
            x_a = x_a.reshape(-1, self.hidden_dim)
            x_a = self.t_attn_layers[i](x_a, r_t, edge_index_t)
            x_a = x_a.reshape(-1, self.num_historical_steps, self.hidden_dim).transpose(0, 1).reshape(-1, self.hidden_dim)
            if self.use_pl2a_tsgformer:
                x_a = self._apply_pl2a_tsgformer(
                    x_a, map_enc_x_pl, edge_index_pl2a, rel_pos_pl2a,
                    head_s, orient_pl_rep, speed_s, pos_s, edge_index_pl2pl, edge_type_pl2pl, i
                )
            else:
                x_a = self.pl2a_attn_layers[i]((map_enc_x_pl.transpose(0, 1).reshape(-1, self.hidden_dim), x_a),
                                               r_pl2a, edge_index_pl2a)
            x_a = x_a.reshape(self.num_historical_steps, -1, self.hidden_dim).transpose(0, 1)

        # Apply TSGFormer to key frames; scene token comes from the last key frame
        scene_token: Optional[torch.Tensor] = None
        for t in self.key_frames:
            if t < self.num_historical_steps:
                x_a_t = x_a[:, t, :]
                pos_t_kf = pos_a[:, t, :2]
                vel_t_kf = vel[:, t, :2]
                head_t_kf = head_a[:, t]
                g_road = self._build_road_gate(
                    pos_t_kf,
                    head_t_kf,
                    vel_t_kf,
                    pos_pl[:, :2],
                    orient_pl,
                    edge_index_pl2pl,
                )

                x_a_enhanced, scene_token = self._apply_tsgformer_batched(
                    x_a_t, pos_t_kf, vel_t_kf, agent_type, agent_batch, g_map=g_road)
                x_a[:, t, :] = x_a_enhanced

        return {'x_a': x_a, 'scene_token': scene_token}
