# Generated by TSG author, 2026.

"""
QCNet Encoder wrapper that uses TSGFormer for agent encoding.

TSGFormer is applied to selected key frames to enrich agent representations
with global scene context.
"""
from typing import Dict, List, Optional

import torch
import torch.nn as nn
from torch_geometric.data import HeteroData, Batch

from modules.qcnet_agent_encoder_with_tsgformer import QCNetAgentEncoderWithTSGFormer
from modules.qcnet_map_encoder import QCNetMapEncoder


class QCNetEncoderWithTSGFormer(nn.Module):

    def __init__(self,
                 dataset: str,
                 input_dim: int,
                 hidden_dim: int,
                 num_historical_steps: int,
                 pl2pl_radius: float,
                 time_span: Optional[int],
                 pl2a_radius: float,
                 a2a_radius: float,
                 num_freq_bands: int,
                 num_map_layers: int,
                 num_agent_layers: int,
                 num_heads: int,
                 head_dim: int,
                 dropout: float,
                 tsgformer_key_frames: Optional[List[int]] = None,
                 num_agent_types: int = 6,
                 num_speed_bins: int = 50,
                 num_spatial_bins: int = 200,
                 num_ttc_bins: int = 100,
                 num_edge_types: int = 21,
                 residual_gate_init: float = -2.0,
                 use_pl2a_tsgformer: bool = True,
                 num_pl2a_edge_types: int = 8,
                 num_ttr_bins: int = 50,
                 **kwargs) -> None:
        super().__init__()

        self.dataset = dataset
        self.input_dim = input_dim
        self.num_historical_steps = num_historical_steps
        self.use_pl2a_tsgformer = use_pl2a_tsgformer

        self.map_encoder = QCNetMapEncoder(
            dataset=dataset,
            input_dim=input_dim,
            hidden_dim=hidden_dim,
            num_historical_steps=num_historical_steps,
            pl2pl_radius=pl2pl_radius,
            num_freq_bands=num_freq_bands,
            num_layers=num_map_layers,
            num_heads=num_heads,
            head_dim=head_dim,
            dropout=dropout,
        )

        self.agent_encoder = QCNetAgentEncoderWithTSGFormer(
            dataset=dataset,
            input_dim=input_dim,
            hidden_dim=hidden_dim,
            num_historical_steps=num_historical_steps,
            time_span=time_span,
            pl2a_radius=pl2a_radius,
            a2a_radius=a2a_radius,
            num_freq_bands=num_freq_bands,
            num_agent_layers=num_agent_layers,
            num_heads=num_heads,
            head_dim=head_dim,
            dropout=dropout,
            tsgformer_key_frames=tsgformer_key_frames,
            num_agent_types=num_agent_types,
            num_speed_bins=num_speed_bins,
            num_spatial_bins=num_spatial_bins,
            num_ttc_bins=num_ttc_bins,
            num_edge_types=num_edge_types,
            residual_gate_init=residual_gate_init,
            use_pl2a_tsgformer=use_pl2a_tsgformer,
            num_pl2a_edge_types=num_pl2a_edge_types,
            num_ttr_bins=num_ttr_bins,
        )

    def _prepare_agent_inputs(self, data: HeteroData, map_enc: Dict[str, torch.Tensor]):
        mask = data['agent']['valid_mask'][:, :self.num_historical_steps].contiguous()
        pos_a = data['agent']['position'][:, :self.num_historical_steps, :self.input_dim].contiguous()
        motion_vector_a = torch.cat([pos_a.new_zeros(data['agent']['num_nodes'], 1, self.input_dim),
                                     pos_a[:, 1:] - pos_a[:, :-1]], dim=1)
        head_a = data['agent']['heading'][:, :self.num_historical_steps].contiguous()
        pos_pl = data['map_polygon']['position'][:, :self.input_dim].contiguous()
        orient_pl = data['map_polygon']['orientation'].contiguous()
        vel = data['agent']['velocity'][:, :self.num_historical_steps, :self.input_dim].contiguous()
        agent_type = data['agent']['type'].long()

        if isinstance(data, Batch):
            batch_s = torch.cat([data['agent']['batch'] + data.num_graphs * t
                                 for t in range(self.num_historical_steps)], dim=0)
            batch_pl = torch.cat([data['map_polygon']['batch'] + data.num_graphs * t
                                  for t in range(self.num_historical_steps)], dim=0)
        else:
            batch_s = torch.arange(self.num_historical_steps, device=pos_a.device).repeat_interleave(
                data['agent']['num_nodes'])
            batch_pl = torch.arange(self.num_historical_steps, device=pos_pl.device).repeat_interleave(
                data['map_polygon']['num_nodes'])

        edge_index_pl2pl = None
        edge_type_pl2pl = None
        if self.use_pl2a_tsgformer and ('map_polygon', 'to', 'map_polygon') in data.edge_types:
            edge_index_pl2pl = data['map_polygon', 'to', 'map_polygon']['edge_index']
            if 'type' in data['map_polygon', 'to', 'map_polygon']:
                edge_type_pl2pl = data['map_polygon', 'to', 'map_polygon']['type']

        return (map_enc['x_pl'], mask, pos_a, motion_vector_a, head_a, pos_pl, orient_pl, vel, agent_type,
                batch_s, batch_pl, edge_index_pl2pl, edge_type_pl2pl)

    def forward(self, data: HeteroData) -> Dict[str, torch.Tensor]:
        map_enc = self.map_encoder(data)
        agent_batch = data['agent']['batch'] if isinstance(data, Batch) else None
        agent_enc = self.agent_encoder(*self._prepare_agent_inputs(data, map_enc),
                                       agent_batch=agent_batch)
        return {**map_enc, **agent_enc}
