# Generated by TSG author, 2026.

"""
TSGFormer components adapted for Argoverse2 agent-agent relationship modeling.
Enhanced with edge types and normalized attention bias.
"""
import math
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

from utils import angle_between_2d_vectors, wrap_angle


def _init_params(module, n_layers: int):
    """Initialize parameters for TSGFormer submodules."""
    if isinstance(module, nn.Linear):
        module.weight.data.normal_(mean=0.0, std=0.02 / math.sqrt(n_layers))
        if module.bias is not None:
            module.bias.data.zero_()
    if isinstance(module, nn.Embedding):
        module.weight.data.normal_(mean=0.0, std=0.02)


# Agent type mapping
# Original: ['vehicle', 'pedestrian', 'motorcyclist', 'cyclist', 'bus', 'static', 'background', 'construction', 'riderless_bicycle', 'unknown']
# Mapped: ['vehicle', 'pedestrian', 'motorcyclist', 'cyclist', 'bus', 'static']
AGENT_TYPE_MAPPING = {
    0: 0,  # vehicle -> vehicle
    1: 1,  # pedestrian -> pedestrian
    2: 2,  # motorcyclist -> motorcyclist
    3: 3,  # cyclist -> cyclist
    4: 4,  # bus -> bus
    5: 5,  # static -> static
    6: 5,  # background -> static
    7: 5,  # construction -> static
    8: 3,  # riderless_bicycle -> cyclist
    9: 5,  # unknown -> static
}


def map_agent_types(agent_types: torch.Tensor) -> torch.Tensor:
    """Map original agent type indices (0-9) to canonical indices (0-5)."""
    device = agent_types.device
    mapping_tensor = torch.tensor([AGENT_TYPE_MAPPING[i] for i in range(10)],
                                  dtype=agent_types.dtype, device=device)
    agent_types_clamped = torch.clamp(agent_types, 0, 9)
    return mapping_tensor[agent_types_clamped]


def compute_edge_types(agent_types: torch.Tensor, num_edge_types: int = 21) -> torch.Tensor:
    """
    Compute pairwise edge types based on agent type combinations.

    Agent types: 0=vehicle, 1=pedestrian, 2=motorcyclist, 3=cyclist, 4=bus, 5=static
    Returns [N, N] edge type indices.
    """
    N = agent_types.size(0)
    agent_i = agent_types.unsqueeze(1).expand(N, N)
    agent_j = agent_types.unsqueeze(0).expand(N, N)

    edge_types = torch.full((N, N), 20, dtype=agent_types.dtype, device=agent_types.device)

    edge_types[(agent_i == 0) & (agent_j == 0)] = 0
    edge_types[((agent_i == 0) & (agent_j == 1)) | ((agent_i == 1) & (agent_j == 0))] = 1
    edge_types[((agent_i == 0) & (agent_j == 2)) | ((agent_i == 2) & (agent_j == 0))] = 2
    edge_types[((agent_i == 0) & (agent_j == 3)) | ((agent_i == 3) & (agent_j == 0))] = 3
    edge_types[((agent_i == 0) & (agent_j == 4)) | ((agent_i == 4) & (agent_j == 0))] = 4
    edge_types[((agent_i == 0) & (agent_j == 5)) | ((agent_i == 5) & (agent_j == 0))] = 5
    edge_types[((agent_i == 1) & (agent_j == 2)) | ((agent_i == 2) & (agent_j == 1))] = 6
    edge_types[((agent_i == 1) & (agent_j == 3)) | ((agent_i == 3) & (agent_j == 1))] = 7
    edge_types[((agent_i == 1) & (agent_j == 4)) | ((agent_i == 4) & (agent_j == 1))] = 8
    edge_types[((agent_i == 1) & (agent_j == 5)) | ((agent_i == 5) & (agent_j == 1))] = 9
    edge_types[(agent_i == 2) & (agent_j == 2)] = 10
    edge_types[((agent_i == 2) & (agent_j == 3)) | ((agent_i == 3) & (agent_j == 2))] = 11
    edge_types[((agent_i == 2) & (agent_j == 4)) | ((agent_i == 4) & (agent_j == 2))] = 12
    edge_types[((agent_i == 2) & (agent_j == 5)) | ((agent_i == 5) & (agent_j == 2))] = 13
    edge_types[(agent_i == 3) & (agent_j == 3)] = 14
    edge_types[((agent_i == 3) & (agent_j == 4)) | ((agent_i == 4) & (agent_j == 3))] = 15
    edge_types[((agent_i == 3) & (agent_j == 5)) | ((agent_i == 5) & (agent_j == 3))] = 16
    edge_types[(agent_i == 4) & (agent_j == 4)] = 17
    edge_types[((agent_i == 4) & (agent_j == 5)) | ((agent_i == 5) & (agent_j == 4))] = 18
    edge_types[(agent_i == 5) & (agent_j == 5)] = 19
    edge_types[(agent_i == 1) & (agent_j == 1)] = 20

    return edge_types


class TSGFormerNodeFeature(nn.Module):
    """Compose node features for TSGFormer from QCNet agent features."""

    def __init__(self, num_heads: int, num_agent_types: int, num_speed_bins: int, hidden_dim: int, n_layers: int):
        super().__init__()
        self.num_heads = num_heads
        self.num_agent_types = num_agent_types
        self.num_speed_bins = num_speed_bins
        self.hidden_dim = hidden_dim

        self.agent_type_encoder = nn.Embedding(num_agent_types + 1, hidden_dim, padding_idx=0)
        self.speed_centrality_encoder = nn.Embedding(num_speed_bins, hidden_dim, padding_idx=0)
        self.centrality_encoder = nn.Linear(1, hidden_dim)
        self.graph_token = nn.Embedding(1, hidden_dim)

        self.apply(lambda m: _init_params(m, n_layers=n_layers))

    def forward(self, agent_features: torch.Tensor, agent_types: torch.Tensor, agent_speeds: torch.Tensor):
        agent_types_mapped = map_agent_types(agent_types)

        node_feature = agent_features
        node_feature = node_feature + self.agent_type_encoder(agent_types_mapped)

        speed_bins = torch.clamp(agent_speeds.float().long(), 0, self.num_speed_bins - 1)
        node_feature = node_feature + self.speed_centrality_encoder(speed_bins)
        node_feature = node_feature + self.centrality_encoder(agent_speeds.unsqueeze(-1).float())

        graph_token_feature = self.graph_token.weight.unsqueeze(0)
        graph_node_feature = torch.cat([graph_token_feature, node_feature.unsqueeze(0)], dim=1)
        return graph_node_feature.squeeze(0)  # [N+1, hidden_dim]


class TSGFormerAttnBias(nn.Module):
    """
    Attention bias for TSGFormer.
    Includes spatial encoding, QCNet-style relative positional encoding, TTC, and edge types.
    All biases are normalized by learnable importance weights.
    """

    def __init__(self, num_heads: int, num_spatial_bins: int, num_ttc_bins: int, num_edge_types: int,
                 hidden_dim: int = 128, n_layers: int = 6, max_distance: float = 6000.0):
        super().__init__()
        self.num_heads = num_heads
        self.num_spatial_bins = num_spatial_bins
        self.num_ttc_bins = num_ttc_bins
        self.num_edge_types = num_edge_types
        self.hidden_dim = hidden_dim
        self.max_distance = max_distance

        self.spatial_pos_encoder = nn.Embedding(num_spatial_bins, num_heads, padding_idx=0)
        from layers.fourier_embedding import FourierEmbedding
        self.rpe_encoder = FourierEmbedding(input_dim=3, hidden_dim=hidden_dim, num_freq_bands=8)
        self.ttc_encoder = nn.Embedding(num_ttc_bins, num_heads, padding_idx=0)
        self.edge_type_encoder = nn.Embedding(num_edge_types, num_heads, padding_idx=0)
        self.graph_token_virtual_distance = nn.Embedding(1, num_heads)

        self.spatial_weight = nn.Parameter(torch.ones(1) * 1.0)
        self.rpe_weight = nn.Parameter(torch.ones(1) * 0.8)
        self.ttc_weight = nn.Parameter(torch.ones(1) * 1.2)
        self.edge_type_weight = nn.Parameter(torch.ones(1) * 1.0)

        edge_type_importance = torch.ones(num_edge_types)
        edge_type_importance[1] = 1.5   # vehicle-pedestrian
        edge_type_importance[3] = 1.5   # vehicle-cyclist
        edge_type_importance[5] = 0.8   # vehicle-static
        edge_type_importance[9] = 0.8   # pedestrian-static
        edge_type_importance[13] = 0.8  # motorcyclist-static
        edge_type_importance[16] = 0.8  # cyclist-static
        edge_type_importance[18] = 0.8  # bus-static
        edge_type_importance[19] = 0.5  # static-static
        self.edge_type_importance = nn.Parameter(edge_type_importance)

        self.temperature = nn.Parameter(torch.ones(1) * 1.0)

        self.apply(lambda m: _init_params(m, n_layers=n_layers))

    @staticmethod
    def compute_ttc(positions: torch.Tensor, velocities: torch.Tensor) -> torch.Tensor:
        """Vectorized Time-to-Collision."""
        rel_pos = positions.unsqueeze(1) - positions.unsqueeze(0)
        rel_vel = velocities.unsqueeze(1) - velocities.unsqueeze(0)

        rel_pos_dot_rel_vel = torch.sum(rel_pos * rel_vel, dim=-1)
        rel_vel_norm_sq = torch.sum(rel_vel * rel_vel, dim=-1)

        ttc = torch.full_like(rel_pos_dot_rel_vel, float("inf"))
        valid_mask = (rel_vel_norm_sq > 1e-6) & (rel_pos_dot_rel_vel < 0)
        ttc[valid_mask] = -rel_pos_dot_rel_vel[valid_mask] / rel_vel_norm_sq[valid_mask]
        ttc.fill_diagonal_(float("inf"))
        return ttc

    def forward(self, positions: torch.Tensor, velocities: torch.Tensor, agent_types: torch.Tensor,
                existing_edge_features: Optional[torch.Tensor] = None,
                g_map: Optional[torch.Tensor] = None):
        num_agents = positions.size(0)
        attn_bias = torch.zeros(num_agents + 1, num_agents + 1, self.num_heads,
                                device=positions.device, dtype=torch.float32)

        rel_pos = positions.unsqueeze(1) - positions.unsqueeze(0)
        x_bins = torch.clamp((rel_pos[:, :, 0] / (self.max_distance / self.num_spatial_bins)).long(),
                             0, self.num_spatial_bins - 1)
        y_bins = torch.clamp((rel_pos[:, :, 1] / (self.max_distance / self.num_spatial_bins)).long(),
                             0, self.num_spatial_bins - 1)
        spatial_bias = self.spatial_pos_encoder(x_bins) + self.spatial_pos_encoder(y_bins)
        spatial_bias = spatial_bias * self.spatial_weight * self.temperature
        attn_bias[1:, 1:, :] = spatial_bias

        distances = torch.norm(rel_pos, p=2, dim=-1)
        angles = torch.atan2(rel_pos[:, :, 1], rel_pos[:, :, 0])
        vel_angles = torch.atan2(velocities[:, 1], velocities[:, 0])
        rel_heading = vel_angles.unsqueeze(1) - vel_angles.unsqueeze(0)
        rel_heading = torch.atan2(torch.sin(rel_heading), torch.cos(rel_heading))
        rpe_features = torch.stack([distances, angles, rel_heading], dim=-1).view(-1, 3)
        rpe_emb = self.rpe_encoder(continuous_inputs=rpe_features.float(), categorical_embs=None)
        rpe_emb = rpe_emb.view(num_agents, num_agents, self.hidden_dim)
        rpe_bias = rpe_emb[:, :, :self.num_heads] * self.rpe_weight * self.temperature
        attn_bias[1:, 1:, :] += rpe_bias

        ttc = self.compute_ttc(positions.float(), velocities.float())
        ttc_bins = torch.clamp((ttc / 1.0).long(), 0, self.num_ttc_bins - 1)
        ttc_bins = torch.where(ttc == float("inf"), self.num_ttc_bins - 1, ttc_bins)
        ttc_bias = self.ttc_encoder(ttc_bins)
        if g_map is not None:
            ttc_bias = ttc_bias * g_map.unsqueeze(-1)
        ttc_bias = ttc_bias * self.ttc_weight * self.temperature
        attn_bias[1:, 1:, :] += ttc_bias

        agent_types_mapped = map_agent_types(agent_types)
        edge_types = compute_edge_types(agent_types_mapped, self.num_edge_types)
        edge_type_bias = self.edge_type_encoder(edge_types)
        edge_type_weights = self.edge_type_importance[edge_types].unsqueeze(-1)
        edge_type_bias = edge_type_bias * edge_type_weights * self.edge_type_weight * self.temperature
        attn_bias[1:, 1:, :] += edge_type_bias

        graph_token_bias = self.graph_token_virtual_distance.weight.view(1, 1, self.num_heads)
        attn_bias[1:, 0, :] = graph_token_bias
        attn_bias[0, :, :] = graph_token_bias

        return attn_bias


class TSGFormerEncoderLayer(nn.Module):
    """Single TSGFormer encoder layer with attention bias support."""

    def __init__(self, hidden_dim: int, num_heads: int, head_dim: int, dropout: float = 0.1,
                 activation_fn: str = "gelu", pre_layernorm: bool = False):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = head_dim
        self.pre_layernorm = pre_layernorm
        self.scale = head_dim ** -0.5

        self.q_proj = nn.Linear(hidden_dim, hidden_dim)
        self.k_proj = nn.Linear(hidden_dim, hidden_dim)
        self.v_proj = nn.Linear(hidden_dim, hidden_dim)
        self.out_proj = nn.Linear(hidden_dim, hidden_dim)
        self.attn_dropout = nn.Dropout(dropout)

        self.record_attn = False
        self.self_attn_layer_norm = nn.LayerNorm(hidden_dim)
        self.final_layer_norm = nn.LayerNorm(hidden_dim)

        self.fc1 = nn.Linear(hidden_dim, hidden_dim * 4)
        self.fc2 = nn.Linear(hidden_dim * 4, hidden_dim)
        self.dropout = nn.Dropout(dropout)
        self.activation_fn = getattr(F, activation_fn)

    def _multi_head_attention_with_bias(self, x: torch.Tensor, attn_bias: Optional[torch.Tensor] = None,
                                        attn_mask: Optional[torch.Tensor] = None):
        is_batched = x.dim() == 3
        if not is_batched:
            x = x.unsqueeze(0)

        batch_size, seq_len, hidden_dim = x.shape

        q = self.q_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)

        attn_scores = torch.matmul(q, k.transpose(-2, -1)) * self.scale

        if attn_bias is not None:
            if attn_bias.dim() == 3:
                attn_bias = attn_bias.permute(2, 0, 1).unsqueeze(0)
            elif attn_bias.dim() == 4:
                attn_bias = attn_bias.permute(0, 3, 1, 2)
            attn_scores = attn_scores + attn_bias

        if attn_mask is not None:
            if attn_mask.dim() == 2:
                attn_mask = attn_mask.unsqueeze(0).unsqueeze(0)
            elif attn_mask.dim() == 3:
                attn_mask = attn_mask.unsqueeze(1)
            attn_scores = attn_scores.masked_fill(attn_mask == 0, float('-inf'))

        attn_weights = F.softmax(attn_scores, dim=-1)
        attn_weights = self.attn_dropout(attn_weights)

        attn_output = torch.matmul(attn_weights, v)
        attn_output = attn_output.transpose(1, 2).contiguous().view(batch_size, seq_len, hidden_dim)
        output = self.out_proj(attn_output)

        if not is_batched:
            output = output.squeeze(0)
            attn_weights = attn_weights.squeeze(0)

        return output, attn_weights

    def forward(self, x: torch.Tensor, attn_bias: Optional[torch.Tensor] = None,
                attn_mask: Optional[torch.Tensor] = None):
        residual = x
        if self.pre_layernorm:
            x = self.self_attn_layer_norm(x)
        x, attn_weights = self._multi_head_attention_with_bias(x, attn_bias=attn_bias, attn_mask=attn_mask)
        if self.record_attn:
            self._last_attn = attn_weights.detach().cpu()
        x = self.dropout(x)
        x = residual + x
        if not self.pre_layernorm:
            x = self.self_attn_layer_norm(x)

        residual = x
        if self.pre_layernorm:
            x = self.final_layer_norm(x)
        x = self.activation_fn(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = residual + x
        if not self.pre_layernorm:
            x = self.final_layer_norm(x)
        return x


class TSGFormerGraphEncoder(nn.Module):
    """TSGFormer graph encoder for QCNet agent interactions."""

    def __init__(self, num_heads: int, num_agent_types: int, num_speed_bins: int, num_spatial_bins: int,
                 num_ttc_bins: int, num_edge_types: int, hidden_dim: int, num_layers: int, dropout: float = 0.1):
        super().__init__()
        self.num_heads = num_heads
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        self.node_feature = TSGFormerNodeFeature(num_heads=num_heads,
                                                 num_agent_types=num_agent_types,
                                                 num_speed_bins=num_speed_bins,
                                                 hidden_dim=hidden_dim,
                                                 n_layers=num_layers)
        self.attn_bias = TSGFormerAttnBias(num_heads=num_heads,
                                           num_spatial_bins=num_spatial_bins,
                                           num_ttc_bins=num_ttc_bins,
                                           num_edge_types=num_edge_types,
                                           hidden_dim=hidden_dim,
                                           n_layers=num_layers,
                                           max_distance=150.0)
        self.layers = nn.ModuleList([
            TSGFormerEncoderLayer(hidden_dim=hidden_dim,
                                  num_heads=num_heads,
                                  head_dim=hidden_dim // num_heads,
                                  dropout=dropout)
            for _ in range(num_layers)
        ])
        self.output_proj = nn.Linear(hidden_dim, hidden_dim)

    def forward(self, agent_features: torch.Tensor, positions: torch.Tensor, velocities: torch.Tensor,
                agent_types: torch.Tensor, existing_edge_features: Optional[torch.Tensor] = None,
                g_map: Optional[torch.Tensor] = None):
        if agent_features.size(0) == 0:
            scene_token = agent_features.new_zeros(self.hidden_dim)
            return agent_features, scene_token
        x = self.node_feature(agent_features, agent_types, torch.norm(velocities.float(), p=2, dim=-1))
        attn_bias = self.attn_bias(positions, velocities, agent_types, existing_edge_features, g_map=g_map)
        for layer in self.layers:
            x = layer(x, attn_bias=attn_bias)
        x = self.output_proj(x)
        return x[1:], x[0]  # (agent_features, scene_token)


# ==============================================================================
# Pl2a TSGFormer Components (Agent-Map Attention with TSGFormer-style bias)
# ==============================================================================

class AgentMapAttnBias(nn.Module):
    """Attention bias for Agent-Map TSGFormer (Spatial, Directional, Edge Type, TTR)."""
    def __init__(self,
                 num_heads: int = 8,
                 num_spatial_bins: int = 100,
                 num_directional_bins: int = 36,
                 num_pl2a_edge_types: int = 8,
                 num_ttr_bins: int = 50,
                 hidden_dim: int = 128,
                 n_layers: int = 2,
                 max_distance: float = 50.0):
        super().__init__()
        self.num_heads = num_heads
        self.num_spatial_bins = num_spatial_bins
        self.num_directional_bins = num_directional_bins
        self.num_pl2a_edge_types = num_pl2a_edge_types
        self.num_ttr_bins = num_ttr_bins
        self.hidden_dim = hidden_dim
        self.max_distance = max_distance
        self.spatial_x_encoder = nn.Embedding(num_spatial_bins, num_heads)
        self.spatial_y_encoder = nn.Embedding(num_spatial_bins, num_heads)
        self.directional_encoder = nn.Embedding(num_directional_bins, num_heads)
        self.edge_type_encoder = nn.Embedding(num_pl2a_edge_types, num_heads)
        self.ttr_encoder = nn.Embedding(num_ttr_bins + 1, num_heads)
        self.gate_spatial = nn.Parameter(torch.tensor(0.0))
        self.gate_directional = nn.Parameter(torch.tensor(0.0))
        self.gate_edge = nn.Parameter(torch.tensor(0.5))
        self.gate_ttr = nn.Parameter(torch.tensor(0.5))
        self.bias_layernorm = nn.LayerNorm(num_heads)
        self.apply(lambda m: _init_params(m, n_layers=n_layers))

    def forward(self, rel_pos: torch.Tensor, relative_angle: torch.Tensor,
                edge_types: torch.Tensor, ttr_values: torch.Tensor) -> torch.Tensor:
        E = rel_pos.size(0)
        device = rel_pos.device
        if E == 0:
            return torch.zeros(0, self.num_heads, device=device)
        x_bins = torch.clamp(
            (rel_pos[:, 0].abs() / self.max_distance * self.num_spatial_bins).long(),
            0, self.num_spatial_bins - 1)
        y_bins = torch.clamp(
            (rel_pos[:, 1].abs() / self.max_distance * self.num_spatial_bins).long(),
            0, self.num_spatial_bins - 1)
        spatial_bias = self.spatial_x_encoder(x_bins) + self.spatial_y_encoder(y_bins)
        angle_normalized = (relative_angle + math.pi) / (2 * math.pi)
        angle_bins = torch.clamp(
            (angle_normalized * self.num_directional_bins).long(),
            0, self.num_directional_bins - 1)
        directional_bias = self.directional_encoder(angle_bins)
        edge_type_bias = self.edge_type_encoder(edge_types)
        ttr_bins = torch.clamp((ttr_values / 10.0 * self.num_ttr_bins).long(), 0, self.num_ttr_bins)
        ttr_bins = torch.where(
            torch.isinf(ttr_values) | (ttr_values > 100.0),
            torch.full_like(ttr_bins, self.num_ttr_bins),
            ttr_bins)
        ttr_bias = self.ttr_encoder(ttr_bins)
        g_s = torch.sigmoid(self.gate_spatial)
        g_d = torch.sigmoid(self.gate_directional)
        g_e = torch.sigmoid(self.gate_edge)
        g_t = torch.sigmoid(self.gate_ttr)
        combined_bias = (g_s * spatial_bias + g_d * directional_bias +
                         g_e * edge_type_bias + g_t * ttr_bias)
        return self.bias_layernorm(combined_bias)


class Pl2aTSGFormerLayer(nn.Module):
    """Polygon-to-Agent attention with TSGFormer-style biases (Agent=Query, Map=Key/Value)."""
    def __init__(self, hidden_dim: int, num_heads: int, head_dim: int, dropout: float,
                 num_freq_bands: int, num_spatial_bins: int = 100, num_directional_bins: int = 36,
                 num_pl2a_edge_types: int = 8, num_ttr_bins: int = 50, max_distance: float = 50.0):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = head_dim
        self.scale = head_dim ** -0.5
        self.attn_bias = AgentMapAttnBias(
            num_heads=num_heads, num_spatial_bins=num_spatial_bins,
            num_directional_bins=num_directional_bins, num_pl2a_edge_types=num_pl2a_edge_types,
            num_ttr_bins=num_ttr_bins, hidden_dim=hidden_dim, max_distance=max_distance)
        self.centrality_encoder = nn.Linear(1, hidden_dim)
        self.q_proj = nn.Linear(hidden_dim, hidden_dim)
        self.k_proj = nn.Linear(hidden_dim, hidden_dim)
        self.v_proj = nn.Linear(hidden_dim, hidden_dim)
        self.layer_norm = nn.LayerNorm(hidden_dim)
        self.dropout = nn.Dropout(dropout)
        self.apply(lambda m: _init_params(m, n_layers=2))

    def forward(self, x_src: torch.Tensor, x_dst: torch.Tensor, edge_index: torch.Tensor,
                rel_pos: torch.Tensor, relative_angle: torch.Tensor, edge_types: torch.Tensor,
                ttr_values: torch.Tensor, centrality: torch.Tensor) -> torch.Tensor:
        E = edge_index.size(1)
        if E == 0:
            return x_dst
        centrality_emb = self.centrality_encoder(centrality.unsqueeze(-1))
        x_src_enhanced = x_src[edge_index[0]] + centrality_emb
        attn_bias = self.attn_bias(rel_pos, relative_angle, edge_types, ttr_values)
        q = self.q_proj(x_dst[edge_index[1]]).view(E, self.num_heads, self.head_dim)
        k = self.k_proj(x_src_enhanced).view(E, self.num_heads, self.head_dim)
        v = self.v_proj(x_src_enhanced).view(E, self.num_heads, self.head_dim)
        attn_scores = (q * k).sum(dim=-1) * self.scale + attn_bias
        dst_nodes = edge_index[1]
        num_dst = x_dst.size(0)
        attn_scores_max = torch.zeros(num_dst, self.num_heads, device=x_dst.device)
        attn_scores_max.scatter_reduce_(0, dst_nodes.unsqueeze(-1).expand(-1, self.num_heads),
                                        attn_scores, reduce='amax', include_self=True)
        attn_scores_exp = torch.exp(attn_scores - attn_scores_max[dst_nodes])
        attn_scores_sum = torch.zeros(num_dst, self.num_heads, device=x_dst.device)
        attn_scores_sum.scatter_add_(0, dst_nodes.unsqueeze(-1).expand(-1, self.num_heads), attn_scores_exp)
        attn_weights = self.dropout(attn_scores_exp / (attn_scores_sum[dst_nodes] + 1e-8))
        weighted_v = (attn_weights.unsqueeze(-1) * v).view(E, self.hidden_dim)
        out = torch.zeros(num_dst, self.hidden_dim, device=x_dst.device)
        out.scatter_add_(0, dst_nodes.unsqueeze(-1).expand(-1, self.hidden_dim), weighted_v)
        return self.layer_norm(x_dst + out)
