# Generated by TSG author, 2026.

import math
from typing import Iterator, Sequence

from torch.utils.data import BatchSampler, Sampler


class LargeSampleAwareBatchSampler(BatchSampler):
    """Batch sampler enforcing a maximum number of large samples per batch."""

    def __init__(self,
                 sampler: Sampler[int],
                 file_sizes_kb: Sequence[float],
                 batch_size: int,
                 large_threshold_kb: int,
                 max_large_per_batch: int,
                 drop_last: bool) -> None:
        if batch_size <= 0:
            raise ValueError('batch_size must be positive')
        if max_large_per_batch <= 0:
            raise ValueError('max_large_per_batch must be positive')
        if max_large_per_batch > batch_size:
            raise ValueError('max_large_per_batch cannot exceed batch_size')
        self.sampler = sampler
        self.file_sizes_kb = file_sizes_kb
        self.batch_size = batch_size
        self.large_threshold_kb = large_threshold_kb
        self.max_large_per_batch = max_large_per_batch
        self.drop_last = drop_last

    def __iter__(self) -> Iterator[list]:
        batch = []
        large_count = 0
        for idx in self.sampler:
            is_large = self.file_sizes_kb[idx] >= self.large_threshold_kb
            if is_large and large_count >= self.max_large_per_batch:
                if len(batch) == 0:
                    yield [idx]
                    continue
                yield batch
                batch = []
                large_count = 0
            batch.append(idx)
            if is_large:
                large_count += 1
            if len(batch) == self.batch_size:
                yield batch
                batch = []
                large_count = 0
        if len(batch) > 0 and not self.drop_last:
            yield batch

    def __len__(self) -> int:
        total = len(self.sampler)
        return total // self.batch_size if self.drop_last else math.ceil(total / self.batch_size)

    def set_epoch(self, epoch: int) -> None:
        if hasattr(self.sampler, 'set_epoch'):
            self.sampler.set_epoch(epoch)

